#pragma once

#include <pebble.h>

#define BACKGROUND_COLOR PBL_IF_COLOR_ELSE(GColorYellow, GColorWhite)
#define MEAL_DOLLAR_COLOR PBL_IF_COLORGColorDarkGreen_ELSE(GColorDarkGreen, GColorBlack)
#define FLEX_DOLLAR_COLOR PBL_IF_COLOR_ELSE(GColorOxfordBlue, GColorWhite)

#define TOTAL_DOLLAR_OFFSET_X PBL_IF_RECT_ELSE(20, 30)
#define TOTAL_DOLLAR_OFFSET_Y PBL_IF_RECT_ELSE(30, 50)

#define MEAL_DOLLAR_OFFSET_X PBL_IF_RECT_ELSE(20, 30)
#define MEAL_DOLLAR_OFFSET_Y PBL_IF_RECT_ELSE(20, 30)

#define FLEX_DOLLAR_OFFSET_X PBL_IF_RECT_ELSE(20, 30)
#define FLEX_DOLLAR_OFFSET_Y PBL_IF_RECT_ELSE(20, 30)
